[package]
name = "mill_core"
version = "0.1.0"
authors = ["Tom Godkin <tomgodkin@pm.me>"]
edition = "2021"
license = "Unlicense OR MIT"
description = "Core library for mill, an OCI-compliant container runtime."

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
