---
on:
  push: {branches: [main]}
  pull_request: {branches: [main]}
name: Test
jobs:
  test:
    name: Test and build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.56.1
        override: true
        components: "rustfmt,clippy"
    - name: Check
      run: make check
    - name: Unit Test
      run: make test-unit
    - name: Build
      run: make build
