---
on:
  push: {branches: [main]}
  pull_request: {branches: [main]}
name: Test
jobs:
  test:
    name: Test and build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.53.0
        override: true
        components: "rustfmt,clippy"
    - name: Install shellspec
      run: |
        wget \
          -qO- \
          https://github.com/shellspec/shellspec/releases/download/0.28.1/shellspec-dist.tar.gz \
          | tar \
            --directory=/usr/local/bin \
            --strip-components=1 \
            -xzf - \
            shellspec/shellspec
    - name: Check
      run: make check
    - name: Unit test
      run: make test-unit
    - name: Build
      run: make build
    - name: Acceptance test
      run: make test-acceptance